### ISSUE TITLE
The class_name prevent other guard plugins to use Ruby::core Process class.

### ISSUE THREAD

**Issue by taiansu** [guard/guard-process#19]
First, thanks for the nice plugin.

However these lines

    module Guard
      class Process < Guard

will shadows the `Ruby::core Process` and affect all the guard plugins in the same project. 

If they have codes like `Process.fork`, they'll get `NoMethodError: private method 'fork' called for Guard::Process:Class`. And have to use `::Process.fork` instead. I tried to delegate `fork`, `kill`, `getpgid` to `::Process` but it doesn't seems to work. Anyway to fix this?

**Comment by e2** [comment]
@talansu - it's correct for anything inside `module Guard` to use `Guard::Process`. 

If something needs Ruby's `Process`, it either should use `::Process`, or that could shouldn't be in the `Guard` module namespace.

Example, it's ok to have a project `Foo` with the file `file.rb` which defines `Foo::File`. And this won't conflict with Ruby's `File` if done properly.

So the question is: what does your code using `Process` look like? It should be using `::Process` if it wants to use Ruby's `Process`.

Please reopen with some same code if you think we should still work this out.
