### ISSUE TITLE
I can't release 1.2.0 (I'm not a gem owner)

### ISSUE THREAD

**Issue by e2** [guard/guard-process#25]
@mkremer, @ahmeij  - I created a release draft here (no changes to actual code, just deps) : https://github.com/guard/guard-process/releases/tag/untagged-6b45f957c6f45d2bfb2f

You can add me if you want. (`gem owner guard-process -a cezary@chronomantic.net`)

**Comment by ahmeij** [comment]
Hi, & thanks for taking this on.

Owner added successfully.
- cezary@chronomantic.net

**Comment by e2** [comment]
Released! Thanks @ahmeij, my pleasure!

**Comment by mkremer** [comment]
Thanks for your help @e2 :)

**Comment by e2** [comment]
Glad to help.
