### ISSUE TITLE
How to run Ruby code from command?

### ISSUE THREAD

**Issue by georgeu2000** [guard/guard-process#26]
The example is:

    :command => 'rails runner Something::ThatGoesOnAndOn'

How run Ruby code?

I tried ruby -e but got `-e:1: unterminated string meets end of file`.

Also, `ruby -e` seems like a hack...

**Comment by mkremer** [comment]
guard-process is designed to run command line processes, so any command line process should do. the easiest way to run ruby code is to save it to a file and run that: ruby /path/to/your/file.rb

**Comment by e2** [comment]
@georgeu2000 - use [guard-yield](https://github.com/guard/guard-yield) instead, which is exactly designed for running Ruby code directly.

**Comment by georgeu2000** [comment]
OK, thanks.
